import type { Notification, NotificationStats } from '../model/notification.types';

export const dummyNotifications: Notification[] = [
  {
    id: 'NOT-001',
    type: 'appointment',
    title: 'New Appointment Request',
    message: 'David Miller has requested an emergency appointment.',
    priority: 'high',
    status: 'unread',
    link: '/appointments',
    patientName: 'David Miller',
    doctorName: 'Dr. Michael Chen',
    appointmentDate: '2026-06-04',
    timeAgo: '5 min ago',
    created_at: '2026-06-04T09:00:00Z',
  },
  {
    id: 'NOT-002',
    type: 'lab_result',
    title: 'Lab Results Ready',
    message: 'Blood work results for Alice Thompson are now available.',
    priority: 'medium',
    status: 'unread',
    link: '/patients/PAT-001',
    patientName: 'Alice Thompson',
    timeAgo: '15 min ago',
    created_at: '2026-06-04T08:45:00Z',
  },
  {
    id: 'NOT-003',
    type: 'prescription',
    title: 'Prescription Refill Request',
    message: 'George Martinez has requested a refill for Lisinopril 10mg.',
    priority: 'medium',
    status: 'unread',
    link: '/pharmacy',
    patientName: 'George Martinez',
    timeAgo: '30 min ago',
    created_at: '2026-06-04T08:30:00Z',
  },
  {
    id: 'NOT-004',
    type: 'billing',
    title: 'Payment Received',
    message: 'Payment of $250.00 received from Patricia Brown for consultation.',
    priority: 'low',
    status: 'read',
    link: '/billing',
    patientName: 'Patricia Brown',
    timeAgo: '1 hour ago',
    created_at: '2026-06-04T08:00:00Z',
    read_at: '2026-06-04T08:15:00Z',
  },
  {
    id: 'NOT-005',
    type: 'system',
    title: 'System Update',
    message: 'Scheduled maintenance will occur tonight at 2:00 AM. Expect 30 minutes of downtime.',
    priority: 'low',
    status: 'read',
    timeAgo: '2 hours ago',
    created_at: '2026-06-04T07:00:00Z',
    read_at: '2026-06-04T07:30:00Z',
  },
  {
    id: 'NOT-006',
    type: 'appointment',
    title: 'Appointment Cancelled',
    message: 'Jennifer Lee has cancelled her 11:00 AM check-up appointment.',
    priority: 'medium',
    status: 'read',
    link: '/appointments',
    patientName: 'Jennifer Lee',
    doctorName: 'Dr. Emily Brown',
    timeAgo: '3 hours ago',
    created_at: '2026-06-04T06:00:00Z',
    read_at: '2026-06-04T06:30:00Z',
  },
  {
    id: 'NOT-007',
    type: 'alert',
    title: 'Low Stock Alert',
    message: 'Ibuprofen 400mg is below reorder level. Current stock: 25 units.',
    priority: 'high',
    status: 'unread',
    link: '/pharmacy',
    timeAgo: '4 hours ago',
    created_at: '2026-06-04T05:00:00Z',
  },
  {
    id: 'NOT-008',
    type: 'message',
    title: 'Message from Administrator',
    message: 'Staff meeting scheduled for Friday at 3:00 PM in Conference Room A.',
    priority: 'low',
    status: 'unread',
    timeAgo: '5 hours ago',
    created_at: '2026-06-04T04:00:00Z',
  },
];

export const dummyNotificationStats: NotificationStats = {
  total: 8,
  unread: 4,
  highPriority: 2,
  todayCount: 6,
};