// features/prescription/components/MedicationSelector.tsx
import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { 
  Search, 
  ChevronRight, 
  Plus,
  Star,
  History,
  AlertCircle
} from 'lucide-react';
import { Button } from '@/shared/ui/button';
import { Input } from '@/shared/ui/input';
import { Badge } from '@/shared/ui/badge';
import { Card } from '@/shared/ui/card';
import { ScrollArea } from '@/shared/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shared/ui/tabs';
import { useMedicationTemplates, useFrequentlyPrescribedMedications } from '../hooks/useMedicationTemplates';
import type { Medication, MedicationTemplate } from '../types';
import { useAuth } from '@/shared/hooks/useAuth';

interface MedicationSelectorProps {
  onSelect: (medication: Medication) => void;
  trigger: React.ReactNode;
}

export const MedicationSelector: React.FC<MedicationSelectorProps> = ({
  onSelect,
  trigger,
}) => {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState<MedicationTemplate | null>(null);
  
  const { user } = useAuth();
  
  const { data: templates, isLoading } = useMedicationTemplates(search);
  const { data: frequentMeds } = useFrequentlyPrescribedMedications(user?.id || '');

  const filteredTemplates = useMemo(() => {
    if (!templates) return [];
    if (!search) return templates;
    
    return templates.filter(
      t => 
        t.name.toLowerCase().includes(search.toLowerCase()) ||
        t.genericName.toLowerCase().includes(search.toLowerCase()) ||
        t.category.toLowerCase().includes(search.toLowerCase())
    );
  }, [templates, search]);

  const categories = useMemo(() => {
    if (!filteredTemplates) return [];
    const cats = new Set(filteredTemplates.map(t => t.category));
    return Array.from(cats);
  }, [filteredTemplates]);

  const handleTemplateSelect = (template: MedicationTemplate) => {
    setSelectedTemplate(template);
  };

  const handleConfirmMedication = () => {
    if (!selectedTemplate) return;
    
    const medication: Medication = {
      id: '', // Will be generated by backend
      drugId: selectedTemplate.id,
      drugName: selectedTemplate.name,
      genericName: selectedTemplate.genericName,
      strength: selectedTemplate.commonDosages[0] || '',
      form: selectedTemplate.forms[0],
      dosage: '',
      frequency: selectedTemplate.commonFrequencies[0] || '',
      duration: '',
      quantity: 30, // Default
      refills: 0,
      instructions: selectedTemplate.defaultInstructions || '',
      startDate: new Date(),
      isPRN: false,
      isControlledSubstance: selectedTemplate.isControlledSubstance,
      schedule: selectedTemplate.schedule,
    };
    
    onSelect(medication);
    setOpen(false);
    setSelectedTemplate(null);
    setSearch('');
  };

  return (
    <>
      {React.cloneElement(trigger as React.ReactElement, {
        onClick: () => setOpen(true),
      })}

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div 
            className="fixed inset-0 bg-black/50 backdrop-blur-sm"
            onClick={() => setOpen(false)}
          />
          
          <Card className="relative z-50 w-full max-w-4xl max-h-[80vh]">
            <div className="p-6">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold">Select Medication</h2>
                <Button 
                  variant="ghost" 
                  size="icon" 
                  onClick={() => setOpen(false)}
                >
                  ✕
                </Button>
              </div>

              {/* Search */}
              <div className="relative mb-6">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
                <Input
                  placeholder="Search medications by name, generic name, or category..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="pl-10"
                />
              </div>

              <div className="grid grid-cols-3 gap-6">
                {/* Left Panel - Medication List */}
                <div className="col-span-2">
                  <Tabs defaultValue="all">
                    <TabsList>
                      <TabsTrigger value="all">All Medications</TabsTrigger>
                      <TabsTrigger value="frequent">
                        <Star className="w-4 h-4 mr-2" />
                        Frequently Used
                      </TabsTrigger>
                      <TabsTrigger value="recent">
                        <History className="w-4 h-4 mr-2" />
                        Recent
                      </TabsTrigger>
                    </TabsList>

                    <TabsContent value="all" className="mt-4">
                      <ScrollArea className="h-[400px]">
                        <div className="space-y-2">
                          {filteredTemplates?.map((template) => (
                            <Button
                              key={template.id}
                              variant={selectedTemplate?.id === template.id ? 'default' : 'outline'}
                              className="w-full justify-between"
                              onClick={() => handleTemplateSelect(template)}
                            >
                              <div className="flex-1 text-left">
                                <div className="font-medium">{template.name}</div>
                                <div className="text-sm text-muted-foreground">
                                  {template.genericName}
                                </div>
                              </div>
                              <div className="flex items-center gap-2">
                                <Badge variant="secondary">
                                  {template.category}
                                </Badge>
                                {template.isControlledSubstance && (
                                  <AlertCircle className="w-4 h-4 text-yellow-500" />
                                )}
                              </div>
                            </Button>
                          ))}
                        </div>
                      </ScrollArea>
                    </TabsContent>

                    <TabsContent value="frequent" className="mt-4">
                      <ScrollArea className="h-[400px]">
                        <div className="space-y-2">
                          {frequentMeds?.map((template) => (
                            <Button
                              key={template.id}
                              variant="outline"
                              className="w-full justify-between"
                              onClick={() => handleTemplateSelect(template)}
                            >
                              <div className="flex-1 text-left">
                                <div className="font-medium">{template.name}</div>
                                <div className="text-sm text-muted-foreground">
                                  {template.genericName}
                                </div>
                              </div>
                              <Star className="w-4 h-4 text-yellow-500" />
                            </Button>
                          ))}
                        </div>
                      </ScrollArea>
                    </TabsContent>

                    <TabsContent value="recent" className="mt-4">
                      <p className="text-muted-foreground">
                        Recent prescriptions will appear here
                      </p>
                    </TabsContent>
                  </Tabs>
                </div>

                {/* Right Panel - Medication Details */}
                <div>
                  {selectedTemplate ? (
                    <div className="space-y-4">
                      <h3 className="text-lg font-semibold">
                        {selectedTemplate.name}
                      </h3>
                      {selectedTemplate.genericName && (
                        <p className="text-muted-foreground">
                          {selectedTemplate.genericName}
                        </p>
                      )}
                      
                      <div className="space-y-2">
                        <h4 className="font-medium">Common Dosages</h4>
                        <div className="flex flex-wrap gap-2">
                          {selectedTemplate.commonDosages.map((dosage) => (
                            <Badge key={dosage} variant="secondary">
                              {dosage}
                            </Badge>
                          ))}
                        </div>
                      </div>

                      <div className="space-y-2">
                        <h4 className="font-medium">Available Forms</h4>
                        <div className="flex flex-wrap gap-2">
                          {selectedTemplate.forms.map((form) => (
                            <Badge key={form} variant="outline">
                              {form}
                            </Badge>
                          ))}
                        </div>
                      </div>

                      {selectedTemplate.defaultInstructions && (
                        <div className="space-y-2">
                          <h4 className="font-medium">Default Instructions</h4>
                          <p className="text-sm text-muted-foreground">
                            {selectedTemplate.defaultInstructions}
                          </p>
                        </div>
                      )}

                      {selectedTemplate.isControlledSubstance && (
                        <div className="p-3 bg-yellow-50 rounded-lg border border-yellow-200">
                          <p className="text-sm font-medium text-yellow-800">
                            Controlled Substance
                          </p>
                          <p className="text-sm text-yellow-600">
                            Schedule {selectedTemplate.schedule}
                          </p>
                        </div>
                      )}

                      <Button
                        className="w-full"
                        onClick={handleConfirmMedication}
                      >
                        <Plus className="w-4 h-4 mr-2" />
                        Add to Prescription
                      </Button>
                    </div>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-full text-center text-muted-foreground">
                      <Search className="w-12 h-12 mb-4" />
                      <p>Select a medication to view details</p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </Card>
        </div>
      )}
    </>
  );
};